---
- name: Déployer Keystone et Glance sur le contrôleur OpenStack
  hosts: controller
  become: yes
  vars_files:
    - /etc/ansible/vault.yml
  collections:
    - community.rabbitmq
    - openstack.cloud
  roles:
    - role: keystone
      tags: keystone
    - role: glance
      tags: glance

- name: Déployer Nova Compute sur le compute OpenStack
  hosts: compute
  become: yes
  vars_files:
    - /etc/ansible/vault.yml
  collections:
    - openstack.cloud
  roles:
    - role: nova-compute
      tags: nova-compute
